spring:
  application:
    name: empik-backend
  datasource:
    url: jdbc:postgresql://172.30.30.14:5432/empik_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/liquibase/liquibase-changeLog.yaml
client:
  ip-api.url: http://ip-api.com/json/
server:
  port: 8090
